// ============================================================
// data.js — Spanish vocabulary, verbs, and practice content
// Expanded for 8th grade: ~300 vocab words, 40 verbs
// ============================================================

const ALL_VOCAB = {

  School:[
    {es:"la escuela",en:"school",pron:"lah es-KWEH-lah",ex:"Voy a la escuela todos los días."},
    {es:"el colegio",en:"school / high school",pron:"el koh-LEH-hyoh",ex:"Mi colegio está cerca de casa."},
    {es:"la clase",en:"class / classroom",pron:"lah KLAH-seh",ex:"La clase de español es interesante."},
    {es:"el cuaderno",en:"notebook",pron:"el kwah-DER-noh",ex:"Necesito un cuaderno nuevo."},
    {es:"la tarea",en:"homework",pron:"lah tah-REH-ah",ex:"Hice mi tarea anoche."},
    {es:"el examen",en:"exam / test",pron:"el ex-AH-men",ex:"El examen es mañana."},
    {es:"la prueba",en:"quiz / test",pron:"lah PRWEH-bah",ex:"Hay una prueba el viernes."},
    {es:"la biblioteca",en:"library",pron:"lah bee-blee-oh-TEK-ah",ex:"Estudio en la biblioteca."},
    {es:"el maestro",en:"teacher (male)",pron:"el mah-EHS-troh",ex:"El maestro explica bien."},
    {es:"la maestra",en:"teacher (female)",pron:"lah mah-EHS-trah",ex:"La maestra es muy simpática."},
    {es:"el profesor",en:"professor / teacher (male)",pron:"el proh-feh-SOR",ex:"El profesor habla muy rápido."},
    {es:"la profesora",en:"professor / teacher (female)",pron:"lah proh-feh-SOH-rah",ex:"La profesora nos ayuda mucho."},
    {es:"el lápiz",en:"pencil",pron:"el LAH-pees",ex:"¿Tienes un lápiz?"},
    {es:"el bolígrafo",en:"pen",pron:"el boh-LEE-grah-foh",ex:"Necesito un bolígrafo azul."},
    {es:"la mochila",en:"backpack",pron:"lah moh-CHEE-lah",ex:"Mi mochila es muy pesada hoy."},
    {es:"el libro",en:"book",pron:"el LEE-broh",ex:"Este libro es muy interesante."},
    {es:"la hoja de papel",en:"sheet of paper",pron:"lah OH-hah deh pah-PEL",ex:"Dame una hoja de papel, por favor."},
    {es:"el horario",en:"schedule",pron:"el oh-RAH-ryoh",ex:"Mi horario tiene seis clases."},
    {es:"la nota",en:"grade / note",pron:"lah NOH-tah",ex:"Saqué una buena nota en el examen."},
    {es:"el recreo",en:"recess / break",pron:"el reh-KREH-oh",ex:"Jugamos durante el recreo."},
    {es:"la cafetería",en:"cafeteria",pron:"lah kah-feh-teh-REE-ah",ex:"Comemos en la cafetería."},
    {es:"el gimnasio",en:"gymnasium",pron:"el heem-NAH-syoh",ex:"Tenemos educación física en el gimnasio."},
    {es:"estudiar",en:"to study",pron:"ehs-too-DYAR",ex:"Necesito estudiar para el examen."},
    {es:"aprender",en:"to learn",pron:"ah-pren-DER",ex:"Me gusta aprender idiomas."},
    {es:"las matemáticas",en:"mathematics",pron:"lahs mah-teh-MAH-tee-kahs",ex:"Las matemáticas son difíciles."},
    {es:"las ciencias",en:"science",pron:"lahs SYEN-syahs",ex:"Me encanta la clase de ciencias."},
    {es:"la historia",en:"history",pron:"lah ees-TOH-ryah",ex:"La historia es mi materia favorita."},
    {es:"el arte",en:"art",pron:"el AR-teh",ex:"Tengo una clase de arte los lunes."},
    {es:"la música",en:"music",pron:"lah MOO-see-kah",ex:"Toco música todos los días."},
    {es:"la educación física",en:"physical education / PE",pron:"lah eh-doo-kah-SYON FEE-see-kah",ex:"La educación física es mi clase favorita."},
  ],

  Family:[
    {es:"la familia",en:"family",pron:"lah fah-MEE-lee-ah",ex:"Mi familia es grande."},
    {es:"los padres",en:"parents",pron:"lohs PAH-drehs",ex:"Mis padres trabajan mucho."},
    {es:"el padre",en:"father",pron:"el PAH-dreh",ex:"Mi padre cocina muy bien."},
    {es:"la madre",en:"mother",pron:"lah MAH-dreh",ex:"Mi madre es doctora."},
    {es:"el hermano",en:"brother",pron:"el er-MAH-noh",ex:"Tengo un hermano mayor."},
    {es:"la hermana",en:"sister",pron:"lah er-MAH-nah",ex:"Mi hermana canta bien."},
    {es:"los abuelos",en:"grandparents",pron:"lohs ah-BWEH-lohs",ex:"Visito a mis abuelos los domingos."},
    {es:"el abuelo",en:"grandfather",pron:"el ah-BWEH-loh",ex:"Mi abuelo tiene ochenta años."},
    {es:"la abuela",en:"grandmother",pron:"lah ah-BWEH-lah",ex:"La abuela hace tamales deliciosos."},
    {es:"el primo",en:"cousin (male)",pron:"el PREE-moh",ex:"Mi primo vive en México."},
    {es:"la prima",en:"cousin (female)",pron:"lah PREE-mah",ex:"Mi prima es muy divertida."},
    {es:"la tía",en:"aunt",pron:"lah TEE-ah",ex:"Mi tía cocina muy bien."},
    {es:"el tío",en:"uncle",pron:"el TEE-oh",ex:"Mi tío es muy gracioso."},
    {es:"el hijo",en:"son",pron:"el EE-hoh",ex:"Es el hijo mayor de la familia."},
    {es:"la hija",en:"daughter",pron:"lah EE-hah",ex:"Es la hija menor de sus padres."},
    {es:"los hijos",en:"children / kids",pron:"lohs EE-hohs",ex:"Tienen tres hijos."},
    {es:"el bebé",en:"baby",pron:"el beh-BEH",ex:"El bebé duerme mucho."},
    {es:"el esposo",en:"husband",pron:"el es-POH-soh",ex:"Su esposo trabaja en un banco."},
    {es:"la esposa",en:"wife",pron:"lah es-POH-sah",ex:"Su esposa es maestra."},
    {es:"los gemelos",en:"twins",pron:"lohs heh-MEH-lohs",ex:"Mis hermanos son gemelos."},
    {es:"mayor",en:"older / elder",pron:"mah-YOR",ex:"Soy el hijo mayor."},
    {es:"menor",en:"younger / youngest",pron:"meh-NOR",ex:"Ella es la menor de tres hermanas."},
  ],

  Food:[
    {es:"el desayuno",en:"breakfast",pron:"el deh-sah-YOO-noh",ex:"El desayuno es la comida más importante."},
    {es:"el almuerzo",en:"lunch",pron:"el ahl-MWER-soh",ex:"Comemos el almuerzo a mediodía."},
    {es:"la cena",en:"dinner",pron:"lah SEH-nah",ex:"La cena está deliciosa."},
    {es:"la comida",en:"food / meal",pron:"lah koh-MEE-dah",ex:"La comida mexicana es deliciosa."},
    {es:"el desayuno",en:"breakfast",pron:"el deh-sah-YOO-noh",ex:"Tomo el desayuno a las siete."},
    {es:"el agua",en:"water",pron:"el AH-gwah",ex:"Bebo mucha agua cada día."},
    {es:"la leche",en:"milk",pron:"lah LEH-cheh",ex:"Bebo leche todas las mañanas."},
    {es:"el jugo",en:"juice",pron:"el HOO-goh",ex:"Me gusta el jugo de naranja."},
    {es:"el pan",en:"bread",pron:"el pan",ex:"Comemos pan con la cena."},
    {es:"el arroz",en:"rice",pron:"el ah-RROHS",ex:"El arroz con frijoles es mi favorito."},
    {es:"los frijoles",en:"beans",pron:"lohs free-HOH-lehs",ex:"Los frijoles son nutritivos."},
    {es:"el pollo",en:"chicken",pron:"el POH-yoh",ex:"Me gusta el pollo con arroz."},
    {es:"la carne",en:"meat",pron:"lah KAR-neh",ex:"La carne a la parrilla es deliciosa."},
    {es:"el pescado",en:"fish (cooked)",pron:"el pes-KAH-doh",ex:"El pescado es muy sano."},
    {es:"las verduras",en:"vegetables",pron:"lahs ver-DOO-rahs",ex:"Como verduras todos los días."},
    {es:"las frutas",en:"fruits",pron:"lahs FROO-tahs",ex:"Me gustan las frutas tropicales."},
    {es:"la manzana",en:"apple",pron:"lah man-SAH-nah",ex:"Como una manzana cada día."},
    {es:"el plátano",en:"banana",pron:"el PLAH-tah-noh",ex:"El plátano es una fruta tropical."},
    {es:"la naranja",en:"orange",pron:"lah nah-RAN-hah",ex:"Las naranjas son ricas en vitamina C."},
    {es:"el queso",en:"cheese",pron:"el KEH-soh",ex:"Me encanta el queso en las quesadillas."},
    {es:"el huevo",en:"egg",pron:"el WEH-voh",ex:"Como huevos en el desayuno."},
    {es:"la sopa",en:"soup",pron:"lah SOH-pah",ex:"La sopa está muy caliente."},
    {es:"la ensalada",en:"salad",pron:"lah en-sah-LAH-dah",ex:"Pido una ensalada con el almuerzo."},
    {es:"el postre",en:"dessert",pron:"el POHS-treh",ex:"El pastel es mi postre favorito."},
    {es:"el helado",en:"ice cream",pron:"el eh-LAH-doh",ex:"El helado de chocolate es delicioso."},
    {es:"el pastel",en:"cake",pron:"el pas-TEL",ex:"Comemos pastel en los cumpleaños."},
    {es:"delicioso",en:"delicious",pron:"deh-lee-SYOH-soh",ex:"La comida está muy deliciosa."},
    {es:"rico",en:"tasty / rich",pron:"REE-koh",ex:"Este plato es muy rico."},
    {es:"tener hambre",en:"to be hungry",pron:"teh-NER AM-breh",ex:"Tengo mucha hambre después de clase."},
    {es:"tener sed",en:"to be thirsty",pron:"teh-NER sed",ex:"Tengo sed. ¿Hay agua?"},
  ],

  Time:[
    {es:"ahora",en:"now",pron:"ah-OH-rah",ex:"Ahora tengo que estudiar."},
    {es:"mañana",en:"tomorrow / morning",pron:"mah-NYAH-nah",ex:"Hasta mañana."},
    {es:"ayer",en:"yesterday",pron:"ah-YEHR",ex:"Ayer fui al parque."},
    {es:"hoy",en:"today",pron:"OY",ex:"Hoy es un buen día."},
    {es:"la semana",en:"week",pron:"lah seh-MAH-nah",ex:"Esta semana tenemos examen."},
    {es:"el mes",en:"month",pron:"el mes",ex:"Este mes es octubre."},
    {es:"el año",en:"year",pron:"el AH-nyoh",ex:"Este año aprendo español."},
    {es:"siempre",en:"always",pron:"SYEM-preh",ex:"Siempre estudio por la noche."},
    {es:"nunca",en:"never",pron:"NOON-kah",ex:"Nunca llego tarde a clase."},
    {es:"a veces",en:"sometimes",pron:"ah BAH-sehs",ex:"A veces voy al gimnasio."},
    {es:"frecuentemente",en:"frequently",pron:"freh-KWEN-teh-men-teh",ex:"Frecuentemente leo libros."},
    {es:"tarde",en:"late / afternoon",pron:"TAR-deh",ex:"Llegué tarde a la escuela."},
    {es:"temprano",en:"early",pron:"tem-PRAH-noh",ex:"Me levanto temprano los lunes."},
    {es:"por la mañana",en:"in the morning",pron:"por lah mah-NYAH-nah",ex:"Estudio por la mañana."},
    {es:"por la tarde",en:"in the afternoon",pron:"por lah TAR-deh",ex:"Voy al parque por la tarde."},
    {es:"por la noche",en:"at night / in the evening",pron:"por lah NOH-cheh",ex:"Hago mi tarea por la noche."},
    {es:"el lunes",en:"Monday",pron:"el LOO-nes",ex:"El lunes tengo matemáticas."},
    {es:"el martes",en:"Tuesday",pron:"el MAR-tes",ex:"El martes hay prueba."},
    {es:"el miércoles",en:"Wednesday",pron:"el MYER-koh-les",ex:"El miércoles voy a la biblioteca."},
    {es:"el jueves",en:"Thursday",pron:"el HWEH-ves",ex:"El jueves tengo educación física."},
    {es:"el viernes",en:"Friday",pron:"el BYER-nes",ex:"El viernes no hay clases."},
    {es:"el fin de semana",en:"weekend",pron:"el feen deh seh-MAH-nah",ex:"El fin de semana voy de compras."},
    {es:"¿Qué hora es?",en:"What time is it?",pron:"keh OH-rah es",ex:"Perdona, ¿qué hora es?"},
    {es:"la medianoche",en:"midnight",pron:"lah meh-dyah-NOH-cheh",ex:"El año nuevo empieza a la medianoche."},
    {es:"el mediodía",en:"noon / midday",pron:"el meh-dyoh-DEE-ah",ex:"Comemos al mediodía."},
  ],

  Adjectives:[
    {es:"difícil",en:"difficult",pron:"dee-FEE-seel",ex:"El español no es tan difícil."},
    {es:"fácil",en:"easy",pron:"FAH-seel",ex:"La tarea de hoy es fácil."},
    {es:"interesante",en:"interesting",pron:"een-teh-reh-SAHN-teh",ex:"La clase es muy interesante."},
    {es:"aburrido",en:"boring",pron:"ah-boo-REE-doh",ex:"La película fue muy aburrida."},
    {es:"importante",en:"important",pron:"eem-por-TAHN-teh",ex:"Es importante practicar cada día."},
    {es:"simpático",en:"nice / friendly",pron:"seem-PAH-tee-koh",ex:"Mi maestro es muy simpático."},
    {es:"antipático",en:"unfriendly / unpleasant",pron:"an-tee-PAH-tee-koh",ex:"Ese chico es muy antipático."},
    {es:"grande",en:"big / great",pron:"GRAHN-deh",ex:"Tengo una familia muy grande."},
    {es:"pequeño",en:"small / little",pron:"peh-KEH-nyoh",ex:"Mi cuarto es pequeño pero cómodo."},
    {es:"nuevo",en:"new",pron:"NWEH-voh",ex:"Tengo un libro nuevo."},
    {es:"viejo",en:"old",pron:"BYEH-hoh",ex:"Este edificio es muy viejo."},
    {es:"bueno",en:"good",pron:"BWEH-noh",ex:"Ella es una buena estudiante."},
    {es:"malo",en:"bad",pron:"MAH-loh",ex:"Tuve un día muy malo."},
    {es:"bonito",en:"pretty / nice",pron:"boh-NEE-toh",ex:"Tiene una voz muy bonita."},
    {es:"feo",en:"ugly",pron:"FEH-oh",ex:"Ese edificio es muy feo."},
    {es:"alto",en:"tall",pron:"AHL-toh",ex:"Mi hermano es muy alto."},
    {es:"bajo",en:"short (height)",pron:"BAH-hoh",ex:"La niña es baja para su edad."},
    {es:"gordo",en:"fat / heavy",pron:"GOR-doh",ex:"El gato está muy gordo."},
    {es:"delgado",en:"thin / slim",pron:"del-GAH-doh",ex:"El corredor es muy delgado."},
    {es:"fuerte",en:"strong",pron:"FWER-teh",ex:"El atleta es muy fuerte."},
    {es:"débil",en:"weak",pron:"DEH-beel",ex:"Me siento débil hoy."},
    {es:"rápido",en:"fast / quick",pron:"RAH-pee-doh",ex:"El tren es muy rápido."},
    {es:"lento",en:"slow",pron:"LEN-toh",ex:"La tortuga es muy lenta."},
    {es:"cansado",en:"tired",pron:"kan-SAH-doh",ex:"Estoy muy cansado después de la práctica."},
    {es:"enfermo",en:"sick / ill",pron:"en-FER-moh",ex:"No fui a la escuela porque estaba enfermo."},
    {es:"contento",en:"happy / content",pron:"kon-TEN-toh",ex:"Estoy muy contento con mi nota."},
    {es:"triste",en:"sad",pron:"TREES-teh",ex:"Estoy triste porque perdimos el partido."},
    {es:"enojado",en:"angry",pron:"eh-noh-HAH-doh",ex:"Mi mamá está enojada conmigo."},
    {es:"asustado",en:"scared / frightened",pron:"ah-soos-TAH-doh",ex:"El niño está asustado por la tormenta."},
    {es:"ocupado",en:"busy",pron:"oh-koo-PAH-doh",ex:"Estoy muy ocupado esta semana."},
    {es:"libre",en:"free / available",pron:"LEE-breh",ex:"¿Estás libre el sábado?"},
    {es:"rico",en:"rich / delicious",pron:"REE-koh",ex:"Esta sopa está muy rica."},
    {es:"pobre",en:"poor",pron:"POH-breh",ex:"El personaje es muy pobre al principio."},
    {es:"joven",en:"young",pron:"HOH-ven",ex:"Mi maestra es muy joven."},
    {es:"caliente",en:"hot",pron:"kah-LYEN-teh",ex:"El café está muy caliente."},
    {es:"frío",en:"cold",pron:"FREE-oh",ex:"El agua está muy fría."},
  ],

  Phrases:[
    {es:"¿Cómo te llamas?",en:"What is your name?",pron:"KOH-moh teh YAH-mahs",ex:"Hola, ¿cómo te llamas?"},
    {es:"Me llamo…",en:"My name is…",pron:"meh YAH-moh",ex:"Me llamo Sofía."},
    {es:"¿Cuántos años tienes?",en:"How old are you?",pron:"KWAHN-tohs AH-nyos TYEH-nes",ex:"¿Cuántos años tienes tú?"},
    {es:"Tengo… años.",en:"I am … years old.",pron:"TEN-goh AH-nyohs",ex:"Tengo catorce años."},
    {es:"¿Dónde vives?",en:"Where do you live?",pron:"DOHN-deh BEE-behs",ex:"¿Dónde vives ahora?"},
    {es:"Vivo en…",en:"I live in…",pron:"BEE-boh en",ex:"Vivo en California."},
    {es:"me gusta",en:"I like",pron:"meh GOOS-tah",ex:"Me gusta mucho la música."},
    {es:"no me gusta",en:"I don't like",pron:"noh meh GOOS-tah",ex:"No me gusta levantarme temprano."},
    {es:"me encanta",en:"I love / I really like",pron:"meh en-KAHN-tah",ex:"Me encanta el chocolate."},
    {es:"tengo que",en:"I have to",pron:"TEN-goh keh",ex:"Tengo que estudiar esta noche."},
    {es:"¿Cómo estás?",en:"How are you? (informal)",pron:"KOH-moh ehs-TAHS",ex:"¡Hola! ¿Cómo estás?"},
    {es:"Estoy bien.",en:"I am fine / well.",pron:"ehs-TOY byen",ex:"Estoy bien, gracias."},
    {es:"Estoy mal.",en:"I am not well.",pron:"ehs-TOY mal",ex:"Estoy mal hoy — tengo fiebre."},
    {es:"Más o menos.",en:"So-so.",pron:"mas oh MEH-nohs",ex:"¿Cómo estás? Más o menos."},
    {es:"por favor",en:"please",pron:"por fah-VOR",ex:"Por favor, habla más despacio."},
    {es:"gracias",en:"thank you",pron:"GRAH-syahs",ex:"Muchas gracias por tu ayuda."},
    {es:"de nada",en:"you're welcome",pron:"deh NAH-dah",ex:"— Gracias. — De nada."},
    {es:"lo siento",en:"I'm sorry",pron:"loh SYEN-toh",ex:"Lo siento, llegué tarde."},
    {es:"perdón",en:"excuse me / pardon",pron:"per-DON",ex:"Perdón, ¿puede repetir?"},
    {es:"con permiso",en:"excuse me (to pass)",pron:"kon per-MEE-soh",ex:"Con permiso, necesito pasar."},
    {es:"¿Cómo se dice…?",en:"How do you say…?",pron:"KOH-moh seh DEE-seh",ex:"¿Cómo se dice 'homework' en español?"},
    {es:"No entiendo.",en:"I don't understand.",pron:"noh en-TYEN-doh",ex:"No entiendo la pregunta."},
    {es:"¿Puede repetir?",en:"Can you repeat?",pron:"PWEH-deh reh-peh-TEER",ex:"¿Puede repetir más despacio?"},
    {es:"Habla más despacio.",en:"Speak more slowly.",pron:"AH-blah mas des-PAH-syoh",ex:"Por favor, habla más despacio."},
    {es:"¿Qué significa…?",en:"What does … mean?",pron:"keh seeg-NEE-fee-kah",ex:"¿Qué significa esta palabra?"},
  ],

  Travel:[
    {es:"el aeropuerto",en:"airport",pron:"el ah-eh-roh-PWER-toh",ex:"El aeropuerto está muy lejos."},
    {es:"el avión",en:"airplane",pron:"el ah-BYON",ex:"El avión sale a las diez."},
    {es:"el hotel",en:"hotel",pron:"el oh-TEL",ex:"El hotel tiene piscina."},
    {es:"el boleto",en:"ticket",pron:"el boh-LEH-toh",ex:"Compré el boleto en línea."},
    {es:"el pasaporte",en:"passport",pron:"el pah-sah-POR-teh",ex:"No olvides tu pasaporte."},
    {es:"la maleta",en:"suitcase",pron:"lah mah-LEH-tah",ex:"Mi maleta es muy pesada."},
    {es:"el tren",en:"train",pron:"el tren",ex:"Tomamos el tren a Madrid."},
    {es:"el autobús",en:"bus",pron:"el ow-toh-BOOS",ex:"El autobús llega en diez minutos."},
    {es:"el taxi",en:"taxi",pron:"el TAK-see",ex:"Tomamos un taxi al hotel."},
    {es:"el metro",en:"subway",pron:"el MEH-troh",ex:"El metro es más rápido que el autobús."},
    {es:"la estación",en:"station",pron:"lah es-tah-SYON",ex:"La estación de tren queda cerca."},
    {es:"el mapa",en:"map",pron:"el MAH-pah",ex:"Necesitamos un mapa de la ciudad."},
    {es:"la ciudad",en:"city",pron:"lah syoo-DAHD",ex:"Nueva York es una ciudad enorme."},
    {es:"el país",en:"country",pron:"el pah-EES",ex:"México es un país muy grande."},
    {es:"la playa",en:"beach",pron:"lah PLAH-yah",ex:"Pasamos el verano en la playa."},
    {es:"las montañas",en:"mountains",pron:"lahs mon-TAH-nyahs",ex:"Las montañas son muy hermosas."},
    {es:"el museo",en:"museum",pron:"el moo-SEH-oh",ex:"Visitamos el museo de arte."},
    {es:"el restaurante",en:"restaurant",pron:"el res-tow-RAN-teh",ex:"El restaurante cierra a las once."},
    {es:"las vacaciones",en:"vacation",pron:"lahs bah-kah-SYOH-nes",ex:"Mis vacaciones son en julio."},
    {es:"el verano",en:"summer",pron:"el beh-RAH-noh",ex:"En verano vamos a la playa."},
  ],

  Hobbies:[
    {es:"el fútbol",en:"soccer",pron:"el FOOT-bol",ex:"Me gusta jugar al fútbol."},
    {es:"el baloncesto",en:"basketball",pron:"el bah-lon-SEHS-toh",ex:"Juego baloncesto los fines de semana."},
    {es:"el béisbol",en:"baseball",pron:"el BAYS-bol",ex:"Mi deporte favorito es el béisbol."},
    {es:"la natación",en:"swimming",pron:"lah nah-tah-SYON",ex:"Practico la natación en verano."},
    {es:"correr",en:"to run / running",pron:"koh-RRER",ex:"Corro cinco kilómetros cada mañana."},
    {es:"leer",en:"to read / reading",pron:"leh-EHR",ex:"Me gusta leer novelas."},
    {es:"dibujar",en:"to draw / drawing",pron:"dee-boo-HAR",ex:"Ella dibuja muy bien."},
    {es:"pintar",en:"to paint / painting",pron:"peen-TAR",ex:"Me gusta pintar los domingos."},
    {es:"cocinar",en:"to cook / cooking",pron:"koh-see-NAR",ex:"Me gusta cocinar con mi mamá."},
    {es:"bailar",en:"to dance / dancing",pron:"bay-LAR",ex:"Bailo salsa con mis amigos."},
    {es:"cantar",en:"to sing / singing",pron:"kan-TAR",ex:"Canta en el coro de la escuela."},
    {es:"tocar la guitarra",en:"to play guitar",pron:"toh-KAR lah gee-TAR-rah",ex:"Toco la guitarra desde los diez años."},
    {es:"tocar el piano",en:"to play piano",pron:"toh-KAR el PYAH-noh",ex:"Mi hermana toca el piano muy bien."},
    {es:"escuchar música",en:"to listen to music",pron:"es-koo-CHAR MOO-see-kah",ex:"Me encanta escuchar música latina."},
    {es:"ver películas",en:"to watch movies",pron:"ver peh-LEE-koo-lahs",ex:"Los viernes vemos películas en casa."},
    {es:"jugar videojuegos",en:"to play video games",pron:"hoo-GAR bee-deh-oh-HWEH-gohs",ex:"Juego videojuegos con mis amigos."},
    {es:"navegar por internet",en:"to browse the internet",pron:"nah-beh-GAR por een-ter-NET",ex:"Navego por internet para hacer la tarea."},
    {es:"el pasatiempo",en:"hobby / pastime",pron:"el pah-sah-TYEM-poh",ex:"Mi pasatiempo favorito es leer."},
    {es:"practicar deportes",en:"to play sports",pron:"prak-tee-KAR deh-POR-tes",ex:"Practico deportes después de la escuela."},
  ],

  Weather:[
    {es:"el tiempo",en:"weather",pron:"el TYEM-poh",ex:"¿Cómo está el tiempo hoy?"},
    {es:"hace calor",en:"it's hot",pron:"AH-seh kah-LOR",ex:"Hoy hace mucho calor."},
    {es:"hace frío",en:"it's cold",pron:"AH-seh FREE-oh",ex:"En invierno hace mucho frío."},
    {es:"hace sol",en:"it's sunny",pron:"AH-seh sol",ex:"Hace sol y quiero salir."},
    {es:"hace viento",en:"it's windy",pron:"AH-seh BYEN-toh",ex:"Hace mucho viento hoy."},
    {es:"llueve",en:"it's raining",pron:"YWEH-veh",ex:"Hoy llueve mucho."},
    {es:"nieva",en:"it's snowing",pron:"NYEH-bah",ex:"Nieva mucho en diciembre."},
    {es:"está nublado",en:"it's cloudy",pron:"es-TAH noo-BLAH-doh",ex:"Está nublado pero no llueve."},
    {es:"la lluvia",en:"rain",pron:"lah YWEE-byah",ex:"La lluvia llegó de repente."},
    {es:"la nieve",en:"snow",pron:"lah NYEH-beh",ex:"Los niños juegan en la nieve."},
    {es:"la tormenta",en:"storm",pron:"lah tor-MEN-tah",ex:"Hay una tormenta esta noche."},
    {es:"el sol",en:"sun",pron:"el sol",ex:"El sol sale a las seis."},
    {es:"la temperatura",en:"temperature",pron:"lah tem-peh-rah-TOO-rah",ex:"La temperatura es de veinte grados."},
    {es:"el pronóstico",en:"forecast",pron:"el proh-NOHS-tee-koh",ex:"El pronóstico dice que lloverá."},
    {es:"el verano",en:"summer",pron:"el beh-RAH-noh",ex:"El verano es muy caluroso aquí."},
    {es:"el invierno",en:"winter",pron:"el een-BYER-noh",ex:"El invierno es frío y corto."},
    {es:"la primavera",en:"spring",pron:"lah pree-mah-BEH-rah",ex:"Las flores crecen en la primavera."},
    {es:"el otoño",en:"autumn / fall",pron:"el oh-TOH-nyoh",ex:"Las hojas caen en el otoño."},
  ],

  Body:[
    {es:"la cabeza",en:"head",pron:"lah kah-BEH-sah",ex:"Me duele la cabeza."},
    {es:"el pelo",en:"hair",pron:"el PEH-loh",ex:"Tiene el pelo largo y negro."},
    {es:"los ojos",en:"eyes",pron:"lohs OH-hohs",ex:"Tiene los ojos azules."},
    {es:"la nariz",en:"nose",pron:"lah nah-REES",ex:"Me pica la nariz."},
    {es:"la boca",en:"mouth",pron:"lah BOH-kah",ex:"Abre la boca para el médico."},
    {es:"los dientes",en:"teeth",pron:"lohs DYEN-tes",ex:"Me lavo los dientes tres veces al día."},
    {es:"las orejas",en:"ears",pron:"lahs oh-REH-hahs",ex:"Tiene las orejas pequeñas."},
    {es:"el cuello",en:"neck",pron:"el KWEH-yoh",ex:"Me duele el cuello."},
    {es:"los hombros",en:"shoulders",pron:"lohs OM-brohs",ex:"Tiene los hombros anchos."},
    {es:"el brazo",en:"arm",pron:"el BRAH-soh",ex:"Se rompió el brazo jugando fútbol."},
    {es:"la mano",en:"hand",pron:"lah MAH-noh",ex:"Lávate las manos antes de comer."},
    {es:"los dedos",en:"fingers",pron:"lohs DEH-dohs",ex:"Tiene diez dedos en las manos."},
    {es:"el pecho",en:"chest",pron:"el PEH-choh",ex:"Le duele el pecho."},
    {es:"el estómago",en:"stomach",pron:"el es-TOH-mah-goh",ex:"Me duele el estómago."},
    {es:"la espalda",en:"back",pron:"lah es-PAL-dah",ex:"Me duele la espalda por cargar la mochila."},
    {es:"la pierna",en:"leg",pron:"lah PYER-nah",ex:"Le duele la pierna después de correr."},
    {es:"la rodilla",en:"knee",pron:"lah roh-DEE-yah",ex:"Se golpeó la rodilla en el partido."},
    {es:"el pie",en:"foot",pron:"el pyeh",ex:"Me duele el pie derecho."},
    {es:"tener fiebre",en:"to have a fever",pron:"teh-NER FYEH-breh",ex:"Tengo fiebre y no puedo ir a la escuela."},
    {es:"estar resfriado",en:"to have a cold",pron:"es-TAR res-free-AH-doh",ex:"Estoy resfriado esta semana."},
  ],

  Home:[
    {es:"la casa",en:"house / home",pron:"lah KAH-sah",ex:"Mi casa está cerca de la escuela."},
    {es:"el apartamento",en:"apartment",pron:"el ah-par-tah-MEN-toh",ex:"Vivimos en un apartamento pequeño."},
    {es:"la cocina",en:"kitchen",pron:"lah koh-SEE-nah",ex:"Mamá cocina en la cocina."},
    {es:"el dormitorio",en:"bedroom",pron:"el dor-mee-TOH-ryoh",ex:"Mi dormitorio es pequeño pero cómodo."},
    {es:"el cuarto",en:"room / bedroom",pron:"el KWAR-toh",ex:"Limpio mi cuarto los sábados."},
    {es:"el baño",en:"bathroom",pron:"el BAH-nyoh",ex:"El baño está al final del pasillo."},
    {es:"la sala",en:"living room",pron:"lah SAH-lah",ex:"Vemos la tele en la sala."},
    {es:"el comedor",en:"dining room",pron:"el koh-meh-DOR",ex:"Cenamos en el comedor."},
    {es:"el garaje",en:"garage",pron:"el gah-RAH-heh",ex:"El carro está en el garaje."},
    {es:"el jardín",en:"garden / yard",pron:"el har-DEEN",ex:"Mi abuela cuida el jardín."},
    {es:"la ventana",en:"window",pron:"lah ben-TAH-nah",ex:"Abre la ventana — hace calor."},
    {es:"la puerta",en:"door",pron:"lah PWER-tah",ex:"Cierra la puerta, por favor."},
    {es:"el piso",en:"floor / story",pron:"el PEE-soh",ex:"Vivimos en el tercer piso."},
    {es:"el techo",en:"ceiling / roof",pron:"el TEH-choh",ex:"El techo de la casa es rojo."},
    {es:"las escaleras",en:"stairs",pron:"lahs es-kah-LEH-rahs",ex:"Sube las escaleras al segundo piso."},
    {es:"el sofá",en:"sofa / couch",pron:"el soh-FAH",ex:"Me siento en el sofá a ver la tele."},
    {es:"la cama",en:"bed",pron:"lah KAH-mah",ex:"Me acuesto en la cama a las diez."},
    {es:"la silla",en:"chair",pron:"lah SEE-yah",ex:"Siéntate en esa silla."},
    {es:"la mesa",en:"table",pron:"lah MEH-sah",ex:"Comemos en la mesa del comedor."},
    {es:"el espejo",en:"mirror",pron:"el es-PEH-hoh",ex:"Me miro en el espejo por las mañanas."},
  ],

  Shopping:[
    {es:"la tienda",en:"store / shop",pron:"lah TYEN-dah",ex:"La tienda cierra a las nueve."},
    {es:"el mercado",en:"market",pron:"el mer-KAH-doh",ex:"Vamos al mercado los sábados."},
    {es:"el supermercado",en:"supermarket",pron:"el soo-per-mer-KAH-doh",ex:"Compramos en el supermercado."},
    {es:"el centro comercial",en:"shopping mall",pron:"el SEN-troh koh-mer-SYAL",ex:"Fui al centro comercial con mis amigos."},
    {es:"¿Cuánto cuesta?",en:"How much does it cost?",pron:"KWAHN-toh KWES-tah",ex:"¿Cuánto cuesta esta camisa?"},
    {es:"el precio",en:"price",pron:"el PREH-syoh",ex:"El precio es razonable."},
    {es:"barato",en:"cheap / inexpensive",pron:"bah-RAH-toh",ex:"Este mercado es muy barato."},
    {es:"caro",en:"expensive",pron:"KAH-roh",ex:"El restaurante es muy caro."},
    {es:"la oferta",en:"sale / offer",pron:"lah oh-FER-tah",ex:"Hay una oferta del cincuenta por ciento."},
    {es:"el descuento",en:"discount",pron:"el des-KWEN-toh",ex:"Me dieron un descuento del veinte por ciento."},
    {es:"la ropa",en:"clothing",pron:"lah ROH-pah",ex:"Necesito comprar ropa nueva."},
    {es:"la camisa",en:"shirt",pron:"lah kah-MEE-sah",ex:"Esa camisa azul me gusta."},
    {es:"los pantalones",en:"pants / trousers",pron:"lohs pan-tah-LOH-nes",ex:"Los pantalones negros son elegantes."},
    {es:"los zapatos",en:"shoes",pron:"lohs sah-PAH-tohs",ex:"Compré unos zapatos nuevos."},
    {es:"la camiseta",en:"t-shirt",pron:"lah kah-mee-SEH-tah",ex:"Me pongo una camiseta y jeans."},
    {es:"el vestido",en:"dress",pron:"el bes-TEE-doh",ex:"Lleva un vestido rojo precioso."},
    {es:"la chaqueta",en:"jacket",pron:"lah chah-KEH-tah",ex:"Ponte la chaqueta — hace frío."},
    {es:"el dinero",en:"money",pron:"el dee-NEH-roh",ex:"No tengo suficiente dinero."},
    {es:"la tarjeta de crédito",en:"credit card",pron:"lah tar-HEH-tah deh KREH-dee-toh",ex:"Pago con tarjeta de crédito."},
    {es:"el recibo",en:"receipt",pron:"el reh-SEE-boh",ex:"Guarda el recibo por si acaso."},
  ],

  // New categories added for greater variety
  Emotions:[
    {es:"la alegría",en:"joy / happiness",pron:"lah ah-leh-GREE-ah",ex:"Su alegría contagia a todos."},
    {es:"la tristeza",en:"sadness",pron:"lah trees-TEH-sah",ex:"Siento tristeza cuando veo esa película."},
    {es:"el miedo",en:"fear",pron:"el MYEH-doh",ex:"Le tiene miedo a las arañas."},
    {es:"la sorpresa",en:"surprise",pron:"lah sor-PREH-sah",ex:"¡Qué sorpresa verte aquí!"},
    {es:"el orgullo",en:"pride",pron:"el or-GOO-yoh",ex:"Los padres sienten orgullo por su hija."},
    {es:"la vergüenza",en:"embarrassment / shame",pron:"lah ber-GWEN-sah",ex:"Sentí mucha vergüenza al caerme."},
    {es:"los celos",en:"jealousy",pron:"lohs SEH-lohs",ex:"Tiene celos de su hermano."},
    {es:"emocionado",en:"excited / emotional",pron:"eh-moh-syoh-NAH-doh",ex:"Estoy muy emocionado por el viaje."},
    {es:"nervioso",en:"nervous",pron:"ner-BYOH-soh",ex:"Estoy nervioso antes del examen."},
    {es:"tranquilo",en:"calm / relaxed",pron:"tran-KEE-loh",ex:"Mantente tranquilo durante el examen."},
    {es:"preocupado",en:"worried",pron:"preh-oh-koo-PAH-doh",ex:"Estoy preocupado por mi nota."},
    {es:"seguro",en:"sure / confident",pron:"seh-GOO-roh",ex:"Me siento seguro con este tema."},
    {es:"avergonzado",en:"embarrassed / ashamed",pron:"ah-ber-gon-SAH-doh",ex:"Me sentí avergonzado frente a todos."},
    {es:"celoso",en:"jealous",pron:"seh-LOH-soh",ex:"Se pone celoso fácilmente."},
    {es:"orgulloso",en:"proud",pron:"or-goo-YOH-soh",ex:"Estoy orgulloso de mis notas."},
  ],

  Community:[
    {es:"el vecino",en:"neighbor",pron:"el beh-SEE-noh",ex:"Mi vecino es muy amable."},
    {es:"el barrio",en:"neighborhood",pron:"el BAR-ryoh",ex:"Vivo en un barrio tranquilo."},
    {es:"el parque",en:"park",pron:"el PAR-keh",ex:"Los niños juegan en el parque."},
    {es:"el hospital",en:"hospital",pron:"el os-pee-TAL",ex:"Mi tía trabaja en el hospital."},
    {es:"el banco",en:"bank",pron:"el BAN-koh",ex:"Papá fue al banco esta mañana."},
    {es:"la farmacia",en:"pharmacy",pron:"lah far-MAH-syah",ex:"Compré medicamentos en la farmacia."},
    {es:"el correo",en:"post office / mail",pron:"el koh-RREH-oh",ex:"Mandé una carta por correo."},
    {es:"la iglesia",en:"church",pron:"lah ee-GLEH-syah",ex:"Vamos a la iglesia los domingos."},
    {es:"el ayuntamiento",en:"city hall",pron:"el ah-yoon-tah-MYEN-toh",ex:"El ayuntamiento está en el centro."},
    {es:"la policía",en:"police",pron:"lah poh-lee-SEE-ah",ex:"Llamamos a la policía."},
    {es:"el bombero",en:"firefighter",pron:"el bom-BEH-roh",ex:"Los bomberos apagaron el incendio."},
    {es:"el médico",en:"doctor",pron:"el MEH-dee-koh",ex:"El médico recetó antibióticos."},
    {es:"la enfermera",en:"nurse",pron:"lah en-fer-MEH-rah",ex:"La enfermera fue muy amable."},
    {es:"el voluntario",en:"volunteer",pron:"el boh-loon-TAH-ryoh",ex:"Soy voluntario en el banco de comida."},
    {es:"la comunidad",en:"community",pron:"lah koh-moo-nee-DAHD",ex:"Trabajamos juntos por la comunidad."},
  ],

  Technology:[
    {es:"el teléfono",en:"telephone / phone",pron:"el teh-LEH-foh-noh",ex:"Llámame por teléfono."},
    {es:"el celular",en:"cell phone",pron:"el seh-loo-LAR",ex:"Mi celular necesita carga."},
    {es:"la computadora",en:"computer",pron:"lah kom-poo-tah-DOH-rah",ex:"Hago la tarea en la computadora."},
    {es:"la tableta",en:"tablet",pron:"lah tah-BLEH-tah",ex:"Leo libros en mi tableta."},
    {es:"el internet",en:"the internet",pron:"el een-ter-NET",ex:"Busco información en el internet."},
    {es:"la red social",en:"social network",pron:"lah red soh-SYAL",ex:"Uso redes sociales para hablar con amigos."},
    {es:"el correo electrónico",en:"email",pron:"el koh-RREH-oh eh-lek-TROH-nee-koh",ex:"Envié un correo electrónico al profesor."},
    {es:"el mensaje de texto",en:"text message",pron:"el men-SAH-heh deh TEKS-toh",ex:"Le mandé un mensaje de texto."},
    {es:"la contraseña",en:"password",pron:"lah kon-trah-SEH-nyah",ex:"No compartas tu contraseña."},
    {es:"la aplicación",en:"app / application",pron:"lah ah-plee-kah-SYON",ex:"Descargué una nueva aplicación."},
    {es:"la pantalla",en:"screen",pron:"lah pan-TAH-yah",ex:"La pantalla de mi teléfono está rota."},
    {es:"cargar",en:"to charge",pron:"kar-GAR",ex:"Necesito cargar mi celular."},
    {es:"descargar",en:"to download",pron:"des-kar-GAR",ex:"Descargué la canción favorita."},
    {es:"en línea",en:"online",pron:"en LEE-neh-ah",ex:"Compré los boletos en línea."},
  ],
};

// ============================================================
// VERBS — 40 essential 8th grade Spanish verbs
// ============================================================
const VERBS = [
  // -AR verbs (regular)
  {inf:"hablar",en:"to speak / talk",type:"-AR",conj:{
    pres:{yo:"hablo",tú:"hablas",él:"habla",nosotros:"hablamos",vosotros:"habláis",ellos:"hablan"},
    pret:{yo:"hablé",tú:"hablaste",él:"habló",nosotros:"hablamos",vosotros:"hablasteis",ellos:"hablaron"},
    fut:{yo:"hablaré",tú:"hablarás",él:"hablará",nosotros:"hablaremos",vosotros:"hablaréis",ellos:"hablarán"}}},
  {inf:"estudiar",en:"to study",type:"-AR",conj:{
    pres:{yo:"estudio",tú:"estudias",él:"estudia",nosotros:"estudiamos",vosotros:"estudiáis",ellos:"estudian"},
    pret:{yo:"estudié",tú:"estudiaste",él:"estudió",nosotros:"estudiamos",vosotros:"estudiasteis",ellos:"estudiaron"},
    fut:{yo:"estudiaré",tú:"estudiarás",él:"estudiará",nosotros:"estudiaremos",vosotros:"estudiaréis",ellos:"estudiarán"}}},
  {inf:"trabajar",en:"to work",type:"-AR",conj:{
    pres:{yo:"trabajo",tú:"trabajas",él:"trabaja",nosotros:"trabajamos",vosotros:"trabajáis",ellos:"trabajan"},
    pret:{yo:"trabajé",tú:"trabajaste",él:"trabajó",nosotros:"trabajamos",vosotros:"trabajasteis",ellos:"trabajaron"},
    fut:{yo:"trabajaré",tú:"trabajarás",él:"trabajará",nosotros:"trabajaremos",vosotros:"trabajaréis",ellos:"trabajarán"}}},
  {inf:"caminar",en:"to walk",type:"-AR",conj:{
    pres:{yo:"camino",tú:"caminas",él:"camina",nosotros:"caminamos",vosotros:"camináis",ellos:"caminan"},
    pret:{yo:"caminé",tú:"caminaste",él:"caminó",nosotros:"caminamos",vosotros:"caminasteis",ellos:"caminaron"},
    fut:{yo:"caminaré",tú:"caminarás",él:"caminará",nosotros:"caminaremos",vosotros:"caminaréis",ellos:"caminarán"}}},
  {inf:"escuchar",en:"to listen",type:"-AR",conj:{
    pres:{yo:"escucho",tú:"escuchas",él:"escucha",nosotros:"escuchamos",vosotros:"escucháis",ellos:"escuchan"},
    pret:{yo:"escuché",tú:"escuchaste",él:"escuchó",nosotros:"escuchamos",vosotros:"escuchasteis",ellos:"escucharon"},
    fut:{yo:"escucharé",tú:"escucharás",él:"escuchará",nosotros:"escucharemos",vosotros:"escucharéis",ellos:"escucharán"}}},
  {inf:"mirar",en:"to look / watch",type:"-AR",conj:{
    pres:{yo:"miro",tú:"miras",él:"mira",nosotros:"miramos",vosotros:"miráis",ellos:"miran"},
    pret:{yo:"miré",tú:"miraste",él:"miró",nosotros:"miramos",vosotros:"mirasteis",ellos:"miraron"},
    fut:{yo:"miraré",tú:"mirarás",él:"mirará",nosotros:"miraremos",vosotros:"miraréis",ellos:"mirarán"}}},
  {inf:"usar",en:"to use",type:"-AR",conj:{
    pres:{yo:"uso",tú:"usas",él:"usa",nosotros:"usamos",vosotros:"usáis",ellos:"usan"},
    pret:{yo:"usé",tú:"usaste",él:"usó",nosotros:"usamos",vosotros:"usasteis",ellos:"usaron"},
    fut:{yo:"usaré",tú:"usarás",él:"usará",nosotros:"usaremos",vosotros:"usaréis",ellos:"usarán"}}},
  {inf:"necesitar",en:"to need",type:"-AR",conj:{
    pres:{yo:"necesito",tú:"necesitas",él:"necesita",nosotros:"necesitamos",vosotros:"necesitáis",ellos:"necesitan"},
    pret:{yo:"necesité",tú:"necesitaste",él:"necesitó",nosotros:"necesitamos",vosotros:"necesitasteis",ellos:"necesitaron"},
    fut:{yo:"necesitaré",tú:"necesitarás",él:"necesitará",nosotros:"necesitaremos",vosotros:"necesitaréis",ellos:"necesitarán"}}},
  {inf:"comprar",en:"to buy",type:"-AR",conj:{
    pres:{yo:"compro",tú:"compras",él:"compra",nosotros:"compramos",vosotros:"compráis",ellos:"compran"},
    pret:{yo:"compré",tú:"compraste",él:"compró",nosotros:"compramos",vosotros:"comprasteis",ellos:"compraron"},
    fut:{yo:"compraré",tú:"comprarás",él:"comprará",nosotros:"compraremos",vosotros:"compraréis",ellos:"comprarán"}}},
  {inf:"llevar",en:"to carry / to wear",type:"-AR",conj:{
    pres:{yo:"llevo",tú:"llevas",él:"lleva",nosotros:"llevamos",vosotros:"lleváis",ellos:"llevan"},
    pret:{yo:"llevé",tú:"llevaste",él:"llevó",nosotros:"llevamos",vosotros:"llevasteis",ellos:"llevaron"},
    fut:{yo:"llevaré",tú:"llevarás",él:"llevará",nosotros:"llevaremos",vosotros:"llevaréis",ellos:"llevarán"}}},
  {inf:"llegar",en:"to arrive",type:"-AR",conj:{
    pres:{yo:"llego",tú:"llegas",él:"llega",nosotros:"llegamos",vosotros:"llegáis",ellos:"llegan"},
    pret:{yo:"llegué",tú:"llegaste",él:"llegó",nosotros:"llegamos",vosotros:"llegasteis",ellos:"llegaron"},
    fut:{yo:"llegaré",tú:"llegarás",él:"llegará",nosotros:"llegaremos",vosotros:"llegaréis",ellos:"llegarán"}}},
  {inf:"buscar",en:"to look for / search",type:"-AR",conj:{
    pres:{yo:"busco",tú:"buscas",él:"busca",nosotros:"buscamos",vosotros:"buscáis",ellos:"buscan"},
    pret:{yo:"busqué",tú:"buscaste",él:"buscó",nosotros:"buscamos",vosotros:"buscasteis",ellos:"buscaron"},
    fut:{yo:"buscaré",tú:"buscarás",él:"buscará",nosotros:"buscaremos",vosotros:"buscaréis",ellos:"buscarán"}}},
  {inf:"ayudar",en:"to help",type:"-AR",conj:{
    pres:{yo:"ayudo",tú:"ayudas",él:"ayuda",nosotros:"ayudamos",vosotros:"ayudáis",ellos:"ayudan"},
    pret:{yo:"ayudé",tú:"ayudaste",él:"ayudó",nosotros:"ayudamos",vosotros:"ayudasteis",ellos:"ayudaron"},
    fut:{yo:"ayudaré",tú:"ayudarás",él:"ayudará",nosotros:"ayudaremos",vosotros:"ayudaréis",ellos:"ayudarán"}}},
  {inf:"pensar",en:"to think",type:"-AR (stem-changing e→ie)",conj:{
    pres:{yo:"pienso",tú:"piensas",él:"piensa",nosotros:"pensamos",vosotros:"pensáis",ellos:"piensan"},
    pret:{yo:"pensé",tú:"pensaste",él:"pensó",nosotros:"pensamos",vosotros:"pensasteis",ellos:"pensaron"},
    fut:{yo:"pensaré",tú:"pensarás",él:"pensará",nosotros:"pensaremos",vosotros:"pensaréis",ellos:"pensarán"}}},
  {inf:"empezar",en:"to begin / start",type:"-AR (stem-changing e→ie)",conj:{
    pres:{yo:"empiezo",tú:"empiezas",él:"empieza",nosotros:"empezamos",vosotros:"empezáis",ellos:"empiezan"},
    pret:{yo:"empecé",tú:"empezaste",él:"empezó",nosotros:"empezamos",vosotros:"empezasteis",ellos:"empezaron"},
    fut:{yo:"empezaré",tú:"empezarás",él:"empezará",nosotros:"empezaremos",vosotros:"empezaréis",ellos:"empezarán"}}},

  // -ER verbs (regular)
  {inf:"comer",en:"to eat",type:"-ER",conj:{
    pres:{yo:"como",tú:"comes",él:"come",nosotros:"comemos",vosotros:"coméis",ellos:"comen"},
    pret:{yo:"comí",tú:"comiste",él:"comió",nosotros:"comimos",vosotros:"comisteis",ellos:"comieron"},
    fut:{yo:"comeré",tú:"comerás",él:"comerá",nosotros:"comeremos",vosotros:"comeréis",ellos:"comerán"}}},
  {inf:"beber",en:"to drink",type:"-ER",conj:{
    pres:{yo:"bebo",tú:"bebes",él:"bebe",nosotros:"bebemos",vosotros:"bebéis",ellos:"beben"},
    pret:{yo:"bebí",tú:"bebiste",él:"bebió",nosotros:"bebimos",vosotros:"bebisteis",ellos:"bebieron"},
    fut:{yo:"beberé",tú:"beberás",él:"beberá",nosotros:"beberemos",vosotros:"beberéis",ellos:"beberán"}}},
  {inf:"leer",en:"to read",type:"-ER",conj:{
    pres:{yo:"leo",tú:"lees",él:"lee",nosotros:"leemos",vosotros:"leéis",ellos:"leen"},
    pret:{yo:"leí",tú:"leíste",él:"leyó",nosotros:"leímos",vosotros:"leísteis",ellos:"leyeron"},
    fut:{yo:"leeré",tú:"leerás",él:"leerá",nosotros:"leeremos",vosotros:"leeréis",ellos:"leerán"}}},
  {inf:"vender",en:"to sell",type:"-ER",conj:{
    pres:{yo:"vendo",tú:"vendes",él:"vende",nosotros:"vendemos",vosotros:"vendéis",ellos:"venden"},
    pret:{yo:"vendí",tú:"vendiste",él:"vendió",nosotros:"vendimos",vosotros:"vendisteis",ellos:"vendieron"},
    fut:{yo:"venderé",tú:"venderás",él:"venderá",nosotros:"venderemos",vosotros:"venderéis",ellos:"venderán"}}},
  {inf:"aprender",en:"to learn",type:"-ER",conj:{
    pres:{yo:"aprendo",tú:"aprendes",él:"aprende",nosotros:"aprendemos",vosotros:"aprendéis",ellos:"aprenden"},
    pret:{yo:"aprendí",tú:"aprendiste",él:"aprendió",nosotros:"aprendimos",vosotros:"aprendisteis",ellos:"aprendieron"},
    fut:{yo:"aprenderé",tú:"aprenderás",él:"aprenderá",nosotros:"aprenderemos",vosotros:"aprenderéis",ellos:"aprenderán"}}},
  {inf:"correr",en:"to run",type:"-ER",conj:{
    pres:{yo:"corro",tú:"corres",él:"corre",nosotros:"corremos",vosotros:"corréis",ellos:"corren"},
    pret:{yo:"corrí",tú:"corriste",él:"corrió",nosotros:"corrimos",vosotros:"corristeis",ellos:"corrieron"},
    fut:{yo:"correré",tú:"correrás",él:"correrá",nosotros:"correremos",vosotros:"correréis",ellos:"correrán"}}},
  {inf:"ver",en:"to see / watch",type:"-ER irregular",conj:{
    pres:{yo:"veo",tú:"ves",él:"ve",nosotros:"vemos",vosotros:"veis",ellos:"ven"},
    pret:{yo:"vi",tú:"viste",él:"vio",nosotros:"vimos",vosotros:"visteis",ellos:"vieron"},
    fut:{yo:"veré",tú:"verás",él:"verá",nosotros:"veremos",vosotros:"veréis",ellos:"verán"}}},

  // -IR verbs (regular)
  {inf:"vivir",en:"to live",type:"-IR",conj:{
    pres:{yo:"vivo",tú:"vives",él:"vive",nosotros:"vivimos",vosotros:"vivís",ellos:"viven"},
    pret:{yo:"viví",tú:"viviste",él:"vivió",nosotros:"vivimos",vosotros:"vivisteis",ellos:"vivieron"},
    fut:{yo:"viviré",tú:"vivirás",él:"vivirá",nosotros:"viviremos",vosotros:"viviréis",ellos:"vivirán"}}},
  {inf:"escribir",en:"to write",type:"-IR",conj:{
    pres:{yo:"escribo",tú:"escribes",él:"escribe",nosotros:"escribimos",vosotros:"escribís",ellos:"escriben"},
    pret:{yo:"escribí",tú:"escribiste",él:"escribió",nosotros:"escribimos",vosotros:"escribisteis",ellos:"escribieron"},
    fut:{yo:"escribiré",tú:"escribirás",él:"escribirá",nosotros:"escribiremos",vosotros:"escribiréis",ellos:"escribirán"}}},
  {inf:"abrir",en:"to open",type:"-IR",conj:{
    pres:{yo:"abro",tú:"abres",él:"abre",nosotros:"abrimos",vosotros:"abrís",ellos:"abren"},
    pret:{yo:"abrí",tú:"abriste",él:"abrió",nosotros:"abrimos",vosotros:"abristeis",ellos:"abrieron"},
    fut:{yo:"abriré",tú:"abrirás",él:"abrirá",nosotros:"abriremos",vosotros:"abriréis",ellos:"abrirán"}}},
  {inf:"recibir",en:"to receive",type:"-IR",conj:{
    pres:{yo:"recibo",tú:"recibes",él:"recibe",nosotros:"recibimos",vosotros:"recibís",ellos:"reciben"},
    pret:{yo:"recibí",tú:"recibiste",él:"recibió",nosotros:"recibimos",vosotros:"recibisteis",ellos:"recibieron"},
    fut:{yo:"recibiré",tú:"recibirás",él:"recibirá",nosotros:"recibiremos",vosotros:"recibiréis",ellos:"recibirán"}}},
  {inf:"subir",en:"to go up / climb",type:"-IR",conj:{
    pres:{yo:"subo",tú:"subes",él:"sube",nosotros:"subimos",vosotros:"subís",ellos:"suben"},
    pret:{yo:"subí",tú:"subiste",él:"subió",nosotros:"subimos",vosotros:"subisteis",ellos:"subieron"},
    fut:{yo:"subiré",tú:"subirás",él:"subirá",nosotros:"subiremos",vosotros:"subiréis",ellos:"subirán"}}},

  // Irregulars — high frequency
  {inf:"ser",en:"to be (permanent)",type:"Irregular",conj:{
    pres:{yo:"soy",tú:"eres",él:"es",nosotros:"somos",vosotros:"sois",ellos:"son"},
    pret:{yo:"fui",tú:"fuiste",él:"fue",nosotros:"fuimos",vosotros:"fuisteis",ellos:"fueron"},
    fut:{yo:"seré",tú:"serás",él:"será",nosotros:"seremos",vosotros:"seréis",ellos:"serán"}}},
  {inf:"estar",en:"to be (temporary / location)",type:"Irregular",conj:{
    pres:{yo:"estoy",tú:"estás",él:"está",nosotros:"estamos",vosotros:"estáis",ellos:"están"},
    pret:{yo:"estuve",tú:"estuviste",él:"estuvo",nosotros:"estuvimos",vosotros:"estuvisteis",ellos:"estuvieron"},
    fut:{yo:"estaré",tú:"estarás",él:"estará",nosotros:"estaremos",vosotros:"estaréis",ellos:"estarán"}}},
  {inf:"tener",en:"to have",type:"Irregular",conj:{
    pres:{yo:"tengo",tú:"tienes",él:"tiene",nosotros:"tenemos",vosotros:"tenéis",ellos:"tienen"},
    pret:{yo:"tuve",tú:"tuviste",él:"tuvo",nosotros:"tuvimos",vosotros:"tuvisteis",ellos:"tuvieron"},
    fut:{yo:"tendré",tú:"tendrás",él:"tendrá",nosotros:"tendremos",vosotros:"tendréis",ellos:"tendrán"}}},
  {inf:"ir",en:"to go",type:"Irregular",conj:{
    pres:{yo:"voy",tú:"vas",él:"va",nosotros:"vamos",vosotros:"vais",ellos:"van"},
    pret:{yo:"fui",tú:"fuiste",él:"fue",nosotros:"fuimos",vosotros:"fuisteis",ellos:"fueron"},
    fut:{yo:"iré",tú:"irás",él:"irá",nosotros:"iremos",vosotros:"iréis",ellos:"irán"}}},
  {inf:"hacer",en:"to do / make",type:"Irregular",conj:{
    pres:{yo:"hago",tú:"haces",él:"hace",nosotros:"hacemos",vosotros:"hacéis",ellos:"hacen"},
    pret:{yo:"hice",tú:"hiciste",él:"hizo",nosotros:"hicimos",vosotros:"hicisteis",ellos:"hicieron"},
    fut:{yo:"haré",tú:"harás",él:"hará",nosotros:"haremos",vosotros:"haréis",ellos:"harán"}}},
  {inf:"poder",en:"can / to be able to",type:"Irregular",conj:{
    pres:{yo:"puedo",tú:"puedes",él:"puede",nosotros:"podemos",vosotros:"podéis",ellos:"pueden"},
    pret:{yo:"pude",tú:"pudiste",él:"pudo",nosotros:"pudimos",vosotros:"pudisteis",ellos:"pudieron"},
    fut:{yo:"podré",tú:"podrás",él:"podrá",nosotros:"podremos",vosotros:"podréis",ellos:"podrán"}}},
  {inf:"querer",en:"to want / love",type:"Irregular",conj:{
    pres:{yo:"quiero",tú:"quieres",él:"quiere",nosotros:"queremos",vosotros:"queréis",ellos:"quieren"},
    pret:{yo:"quise",tú:"quisiste",él:"quiso",nosotros:"quisimos",vosotros:"quisisteis",ellos:"quisieron"},
    fut:{yo:"querré",tú:"querrás",él:"querrá",nosotros:"querremos",vosotros:"querréis",ellos:"querrán"}}},
  {inf:"saber",en:"to know (facts)",type:"Irregular",conj:{
    pres:{yo:"sé",tú:"sabes",él:"sabe",nosotros:"sabemos",vosotros:"sabéis",ellos:"saben"},
    pret:{yo:"supe",tú:"supiste",él:"supo",nosotros:"supimos",vosotros:"supisteis",ellos:"supieron"},
    fut:{yo:"sabré",tú:"sabrás",él:"sabrá",nosotros:"sabremos",vosotros:"sabréis",ellos:"sabrán"}}},
  {inf:"conocer",en:"to know (people/places)",type:"Irregular (yo go)",conj:{
    pres:{yo:"conozco",tú:"conoces",él:"conoce",nosotros:"conocemos",vosotros:"conocéis",ellos:"conocen"},
    pret:{yo:"conocí",tú:"conociste",él:"conoció",nosotros:"conocimos",vosotros:"conocisteis",ellos:"conocieron"},
    fut:{yo:"conoceré",tú:"conocerás",él:"conocerá",nosotros:"conoceremos",vosotros:"conoceréis",ellos:"conocerán"}}},
  {inf:"decir",en:"to say / tell",type:"Irregular",conj:{
    pres:{yo:"digo",tú:"dices",él:"dice",nosotros:"decimos",vosotros:"decís",ellos:"dicen"},
    pret:{yo:"dije",tú:"dijiste",él:"dijo",nosotros:"dijimos",vosotros:"dijisteis",ellos:"dijeron"},
    fut:{yo:"diré",tú:"dirás",él:"dirá",nosotros:"diremos",vosotros:"diréis",ellos:"dirán"}}},
  {inf:"venir",en:"to come",type:"Irregular",conj:{
    pres:{yo:"vengo",tú:"vienes",él:"viene",nosotros:"venimos",vosotros:"venís",ellos:"vienen"},
    pret:{yo:"vine",tú:"viniste",él:"vino",nosotros:"vinimos",vosotros:"vinisteis",ellos:"vinieron"},
    fut:{yo:"vendré",tú:"vendrás",él:"vendrá",nosotros:"vendremos",vosotros:"vendréis",ellos:"vendrán"}}},
  {inf:"salir",en:"to leave / go out",type:"Irregular (yo go)",conj:{
    pres:{yo:"salgo",tú:"sales",él:"sale",nosotros:"salimos",vosotros:"salís",ellos:"salen"},
    pret:{yo:"salí",tú:"saliste",él:"salió",nosotros:"salimos",vosotros:"salisteis",ellos:"salieron"},
    fut:{yo:"saldré",tú:"saldrás",él:"saldrá",nosotros:"saldremos",vosotros:"saldréis",ellos:"saldrán"}}},
  {inf:"poner",en:"to put / place",type:"Irregular (yo go)",conj:{
    pres:{yo:"pongo",tú:"pones",él:"pone",nosotros:"ponemos",vosotros:"ponéis",ellos:"ponen"},
    pret:{yo:"puse",tú:"pusiste",él:"puso",nosotros:"pusimos",vosotros:"pusisteis",ellos:"pusieron"},
    fut:{yo:"pondré",tú:"pondrás",él:"pondrá",nosotros:"pondremos",vosotros:"pondréis",ellos:"pondrán"}}},
  {inf:"traer",en:"to bring",type:"Irregular (yo go)",conj:{
    pres:{yo:"traigo",tú:"traes",él:"trae",nosotros:"traemos",vosotros:"traéis",ellos:"traen"},
    pret:{yo:"traje",tú:"trajiste",él:"trajo",nosotros:"trajimos",vosotros:"trajisteis",ellos:"trajeron"},
    fut:{yo:"traeré",tú:"traerás",él:"traerá",nosotros:"traeremos",vosotros:"traeréis",ellos:"traerán"}}},
  {inf:"dar",en:"to give",type:"Irregular",conj:{
    pres:{yo:"doy",tú:"das",él:"da",nosotros:"damos",vosotros:"dais",ellos:"dan"},
    pret:{yo:"di",tú:"diste",él:"dio",nosotros:"dimos",vosotros:"disteis",ellos:"dieron"},
    fut:{yo:"daré",tú:"darás",él:"dará",nosotros:"daremos",vosotros:"daréis",ellos:"darán"}}},
  // Stem-changing
  {inf:"dormir",en:"to sleep",type:"-IR (stem o→ue)",conj:{
    pres:{yo:"duermo",tú:"duermes",él:"duerme",nosotros:"dormimos",vosotros:"dormís",ellos:"duermen"},
    pret:{yo:"dormí",tú:"dormiste",él:"durmió",nosotros:"dormimos",vosotros:"dormisteis",ellos:"durmieron"},
    fut:{yo:"dormiré",tú:"dormirás",él:"dormirá",nosotros:"dormiremos",vosotros:"dormiréis",ellos:"dormirán"}}},
  {inf:"jugar",en:"to play (a game/sport)",type:"-AR (stem u→ue)",conj:{
    pres:{yo:"juego",tú:"juegas",él:"juega",nosotros:"jugamos",vosotros:"jugáis",ellos:"juegan"},
    pret:{yo:"jugué",tú:"jugaste",él:"jugó",nosotros:"jugamos",vosotros:"jugasteis",ellos:"jugaron"},
    fut:{yo:"jugaré",tú:"jugarás",él:"jugará",nosotros:"jugaremos",vosotros:"jugaréis",ellos:"jugarán"}}},
  {inf:"pedir",en:"to ask for / order",type:"-IR (stem e→i)",conj:{
    pres:{yo:"pido",tú:"pides",él:"pide",nosotros:"pedimos",vosotros:"pedís",ellos:"piden"},
    pret:{yo:"pedí",tú:"pediste",él:"pidió",nosotros:"pedimos",vosotros:"pedisteis",ellos:"pidieron"},
    fut:{yo:"pediré",tú:"pedirás",él:"pedirá",nosotros:"pediremos",vosotros:"pediréis",ellos:"pedirán"}}},
  {inf:"servir",en:"to serve",type:"-IR (stem e→i)",conj:{
    pres:{yo:"sirvo",tú:"sirves",él:"sirve",nosotros:"servimos",vosotros:"servís",ellos:"sirven"},
    pret:{yo:"serví",tú:"serviste",él:"sirvió",nosotros:"servimos",vosotros:"servisteis",ellos:"sirvieron"},
    fut:{yo:"serviré",tú:"servirás",él:"servirá",nosotros:"serviremos",vosotros:"serviréis",ellos:"servirán"}}},
];

// ============================================================
// LISTENING BANK — static fallback phrases
// ============================================================
const LISTENING_BANK = [
  {es:"Tengo mucha tarea esta noche.",q:"What does the speaker have a lot of tonight?",ans:"homework",hint:"tarea = homework"},
  {es:"Mi familia come la cena juntos.",q:"What does this family do together?",ans:"eat dinner",hint:"comer = to eat, juntos = together"},
  {es:"El examen de español es mañana.",q:"When is the Spanish exam?",ans:"tomorrow",hint:"mañana = tomorrow"},
  {es:"Me gusta mucho la música latina.",q:"What does the speaker like?",ans:"latin music",hint:"música = music"},
  {es:"Vivo cerca de la biblioteca.",q:"Where does the speaker live near?",ans:"library",hint:"biblioteca = library"},
  {es:"Mi hermana tiene quince años.",q:"How old is the sister?",ans:"15",hint:"quince = fifteen"},
  {es:"Hoy tengo que estudiar para el examen.",q:"What must the speaker do today?",ans:"study for the exam",hint:"estudiar = to study"},
  {es:"La clase de español es muy interesante.",q:"How is the class described?",ans:"interesting",hint:"interesante = interesting"},
  {es:"Mis padres trabajan todos los días.",q:"Who works every day?",ans:"parents",hint:"padres = parents"},
  {es:"Hace mucho calor hoy.",q:"What is the weather like?",ans:"very hot",hint:"calor = heat, hace calor = it is hot"},
  {es:"Necesito comprar un bolígrafo nuevo.",q:"What does the speaker need to buy?",ans:"a new pen",hint:"bolígrafo = pen, comprar = to buy"},
  {es:"El fin de semana voy al parque con mi familia.",q:"Where does the speaker go on the weekend?",ans:"the park",hint:"fin de semana = weekend, parque = park"},
  {es:"No me gusta levantarme temprano.",q:"What does the speaker not like doing?",ans:"waking up early",hint:"levantarse = to get up, temprano = early"},
  {es:"Tengo que limpiar mi cuarto antes de salir.",q:"What must the speaker do before leaving?",ans:"clean their room",hint:"limpiar = to clean, cuarto = room"},
  {es:"Me encanta jugar fútbol con mis amigos.",q:"What does the speaker love doing?",ans:"playing soccer with friends",hint:"jugar = to play, fútbol = soccer"},
];

// ============================================================
// SPEAKING BANK — static fallback phrases
// ============================================================
const SPEAKING_BANK = [
  {en:"I like to eat breakfast with my family.",es:"Me gusta desayunar con mi familia.",hint:"me gusta... con mi familia"},
  {en:"I have to do my homework tonight.",es:"Tengo que hacer mi tarea esta noche.",hint:"tengo que hacer..."},
  {en:"My brother goes to school every day.",es:"Mi hermano va a la escuela todos los días.",hint:"va a la escuela..."},
  {en:"The Spanish exam is difficult.",es:"El examen de español es difícil.",hint:"el examen... es..."},
  {en:"I live near the library.",es:"Vivo cerca de la biblioteca.",hint:"vivo cerca de..."},
  {en:"We eat dinner together at home.",es:"Comemos la cena juntos en casa.",hint:"comemos... juntos"},
  {en:"Yesterday I studied for two hours.",es:"Ayer estudié por dos horas.",hint:"ayer estudié..."},
  {en:"Please speak more slowly.",es:"Por favor, habla más despacio.",hint:"por favor, habla..."},
  {en:"My grandparents are very nice.",es:"Mis abuelos son muy simpáticos.",hint:"mis abuelos son..."},
  {en:"I want to learn Spanish well.",es:"Quiero aprender español bien.",hint:"quiero aprender..."},
  {en:"On weekends I play soccer with my friends.",es:"Los fines de semana juego fútbol con mis amigos.",hint:"los fines de semana... con mis amigos"},
  {en:"I need to clean my room before going out.",es:"Necesito limpiar mi cuarto antes de salir.",hint:"necesito limpiar... antes de"},
  {en:"My teacher is very friendly and helpful.",es:"Mi maestra es muy simpática y útil.",hint:"mi maestra es muy..."},
  {en:"I don't understand the question.",es:"No entiendo la pregunta.",hint:"no entiendo..."},
  {en:"It is very hot today.",es:"Hace mucho calor hoy.",hint:"hace... hoy"},
];

// ============================================================
// ENCOURAGEMENTS
// ============================================================
const ENCOURAGEMENTS = [
  {q:'"Every expert was once a beginner."',      a:"You showed up today — that\'s already a win! 🏆"},
  {q:'"Un poco cada día." (A little each day.)', a:"Consistency is your superpower. ¡Tú puedes!"},
  {q:'"The secret is to start."',                a:"You\'re doing it. Keep the momentum going!"},
  {q:'"Practice makes progress, not perfection."',a:"Each session makes Spanish feel more natural."},
  {q:'"Language is the road map of a culture."', a:"You\'re unlocking a whole new world! 🌎"},
  {q:'"It does not matter how slowly you go as long as you do not stop."',a:"Slow progress is still progress. ¡Sigue adelante!"},
  {q:'"The more languages you know, the more you are human."',a:"Your brain is growing every session. Science!"},
  {q:'"You don\'t have to be great to start, but you have to start to be great."',a:"Every word you learn is a step forward. ¡Vamos!"},
];
