// ============================================================
// data.js — All Spanish vocabulary, verbs, and practice content
// ============================================================

const ALL_VOCAB = {
  School:[
    {es:"la escuela",en:"school",pron:"lah es-KWEH-lah",ex:"Voy a la escuela todos los días."},
    {es:"el cuaderno",en:"notebook",pron:"el kwah-DER-noh",ex:"Necesito un cuaderno nuevo."},
    {es:"la tarea",en:"homework",pron:"lah tah-REH-ah",ex:"Hice mi tarea anoche."},
    {es:"el examen",en:"exam / test",pron:"el ex-AH-men",ex:"El examen es mañana."},
    {es:"la biblioteca",en:"library",pron:"lah bee-blee-oh-TEK-ah",ex:"Estudio en la biblioteca."},
    {es:"el maestro",en:"teacher (male)",pron:"el mah-EHS-troh",ex:"El maestro explica bien."},
    {es:"la maestra",en:"teacher (female)",pron:"lah mah-EHS-trah",ex:"La maestra es muy simpática."},
    {es:"el lápiz",en:"pencil",pron:"el LAH-pees",ex:"¿Tienes un lápiz?"},
    {es:"el bolígrafo",en:"pen",pron:"el boh-LEE-grah-foh",ex:"Necesito un bolígrafo azul."},
    {es:"la mochila",en:"backpack",pron:"lah moh-CHEE-lah",ex:"Mi mochila es pesada hoy."},
  ],
  Family:[
    {es:"la familia",en:"family",pron:"lah fah-MEE-lee-ah",ex:"Mi familia es grande."},
    {es:"los padres",en:"parents",pron:"lohs PAH-drehs",ex:"Mis padres trabajan mucho."},
    {es:"el hermano",en:"brother",pron:"el er-MAH-noh",ex:"Tengo un hermano mayor."},
    {es:"la hermana",en:"sister",pron:"lah er-MAH-nah",ex:"Mi hermana canta bien."},
    {es:"los abuelos",en:"grandparents",pron:"lohs ah-BWEH-lohs",ex:"Visito a mis abuelos los domingos."},
    {es:"el primo",en:"cousin (male)",pron:"el PREE-moh",ex:"Mi primo vive en México."},
    {es:"la tía",en:"aunt",pron:"lah TEE-ah",ex:"Mi tía cocina muy bien."},
    {es:"el tío",en:"uncle",pron:"el TEE-oh",ex:"Mi tío es muy gracioso."},
  ],
  Food:[
    {es:"el desayuno",en:"breakfast",pron:"el deh-sah-YOO-noh",ex:"El desayuno es importante."},
    {es:"el almuerzo",en:"lunch",pron:"el ahl-MWER-soh",ex:"Comemos el almuerzo a mediodía."},
    {es:"la cena",en:"dinner",pron:"lah SEH-nah",ex:"La cena está deliciosa."},
    {es:"las frutas",en:"fruits",pron:"lahs FROO-tahs",ex:"Me gustan las frutas tropicales."},
    {es:"el agua",en:"water",pron:"el AH-gwah",ex:"Bebo mucha agua cada día."},
    {es:"el pollo",en:"chicken",pron:"el POH-yoh",ex:"Me gusta el pollo con arroz."},
    {es:"el arroz",en:"rice",pron:"el ah-RROHS",ex:"El arroz con frijoles es rico."},
    {es:"los frijoles",en:"beans",pron:"lohs free-HOH-lehs",ex:"Los frijoles son muy nutritivos."},
  ],
  Time:[
    {es:"ahora",en:"now",pron:"ah-OH-rah",ex:"Ahora tengo que estudiar."},
    {es:"mañana",en:"tomorrow / morning",pron:"mah-NYAH-nah",ex:"Hasta mañana."},
    {es:"ayer",en:"yesterday",pron:"ah-YEHR",ex:"Ayer fui al parque."},
    {es:"la semana",en:"week",pron:"lah seh-MAH-nah",ex:"Esta semana tenemos un examen."},
    {es:"el año",en:"year",pron:"el AH-nyoh",ex:"Este año aprendo español."},
    {es:"hoy",en:"today",pron:"OY",ex:"Hoy es un buen día."},
    {es:"siempre",en:"always",pron:"SYEM-preh",ex:"Siempre estudio por la noche."},
    {es:"nunca",en:"never",pron:"NOON-kah",ex:"Nunca llego tarde a clase."},
  ],
  Adjectives:[
    {es:"difícil",en:"difficult",pron:"dee-FEE-seel",ex:"El español no es tan difícil."},
    {es:"fácil",en:"easy",pron:"FAH-seel",ex:"La tarea es fácil hoy."},
    {es:"interesante",en:"interesting",pron:"een-teh-reh-SAHN-teh",ex:"La clase es muy interesante."},
    {es:"aburrido",en:"boring",pron:"ah-boo-REE-doh",ex:"La película fue muy aburrida."},
    {es:"importante",en:"important",pron:"eem-por-TAHN-teh",ex:"Es importante practicar cada día."},
    {es:"simpático",en:"nice / friendly",pron:"seem-PAH-tee-koh",ex:"Mi maestro es muy simpático."},
    {es:"grande",en:"big / great",pron:"GRAHN-deh",ex:"Tengo una familia muy grande."},
    {es:"pequeño",en:"small / little",pron:"peh-KEH-nyoh",ex:"Mi cuarto es pequeño pero cómodo."},
  ],
  Phrases:[
    {es:"¿Cómo te llamas?",en:"What is your name?",pron:"KOH-moh teh YAH-mahs",ex:"¿Cómo te llamas tú?"},
    {es:"¿Cuántos años tienes?",en:"How old are you?",pron:"KWAHN-tohs AH-nyos TYEH-nes",ex:"¿Cuántos años tienes tú?"},
    {es:"¿Dónde vives?",en:"Where do you live?",pron:"DOHN-deh BEE-behs",ex:"¿Dónde vives ahora?"},
    {es:"me gusta",en:"I like",pron:"meh GOOS-tah",ex:"Me gusta mucho la música."},
    {es:"tengo que",en:"I have to",pron:"TEN-goh keh",ex:"Tengo que estudiar esta noche."},
    {es:"¿Cómo estás?",en:"How are you?",pron:"KOH-moh ehs-TAHS",ex:"¡Buenos días! ¿Cómo estás?"},
    {es:"por favor",en:"please",pron:"por fah-VOR",ex:"Por favor, habla más despacio."},
    {es:"muchas gracias",en:"thank you very much",pron:"MOO-chahs GRAH-syahs",ex:"Muchas gracias por tu ayuda."},
  ],
  Travel:[
    {es:"el aeropuerto",en:"airport",pron:"el ah-eh-roh-PWER-toh",ex:"El aeropuerto está muy lejos."},
    {es:"el hotel",en:"hotel",pron:"el oh-TEL",ex:"El hotel tiene piscina."},
    {es:"el boleto",en:"ticket",pron:"el boh-LEH-toh",ex:"Compré el boleto en línea."},
    {es:"el pasaporte",en:"passport",pron:"el pah-sah-POR-teh",ex:"No olvides tu pasaporte."},
    {es:"la maleta",en:"suitcase",pron:"lah mah-LEH-tah",ex:"Mi maleta es muy pesada."},
  ],
  Hobbies:[
    {es:"el fútbol",en:"soccer",pron:"el FOOT-bol",ex:"Me gusta jugar al fútbol."},
    {es:"la música",en:"music",pron:"lah MOO-see-kah",ex:"Toco música todos los días."},
    {es:"leer",en:"to read",pron:"leh-EHR",ex:"Me gusta leer novelas."},
    {es:"dibujar",en:"to draw",pron:"dee-boo-HAR",ex:"Ella dibuja muy bien."},
    {es:"cocinar",en:"to cook",pron:"koh-see-NAR",ex:"Me gusta cocinar con mi mamá."},
  ],
  Weather:[
    {es:"hace calor",en:"it's hot",pron:"AH-seh kah-LOR",ex:"Hoy hace mucho calor."},
    {es:"hace frío",en:"it's cold",pron:"AH-seh FREE-oh",ex:"En invierno hace frío."},
    {es:"llueve",en:"it's raining",pron:"YWEH-veh",ex:"Hoy llueve mucho."},
    {es:"hace sol",en:"it's sunny",pron:"AH-seh sol",ex:"Hace sol y quiero salir."},
    {es:"el tiempo",en:"the weather",pron:"el TYEM-poh",ex:"¿Cómo está el tiempo hoy?"},
  ],
  Body:[
    {es:"la cabeza",en:"head",pron:"lah kah-BEH-sah",ex:"Me duele la cabeza."},
    {es:"los ojos",en:"eyes",pron:"lohs OH-hohs",ex:"Tiene los ojos verdes."},
    {es:"las manos",en:"hands",pron:"lahs MAH-nohs",ex:"Lávate las manos."},
    {es:"el estómago",en:"stomach",pron:"el ehs-TOH-mah-goh",ex:"Me duele el estómago."},
    {es:"la nariz",en:"nose",pron:"lah nah-REES",ex:"La nariz de mi perro es fría."},
  ],
  Home:[
    {es:"la cocina",en:"kitchen",pron:"lah koh-SEE-nah",ex:"Cocinamos en la cocina."},
    {es:"el dormitorio",en:"bedroom",pron:"el dor-mee-TOH-ryoh",ex:"Mi dormitorio es pequeño."},
    {es:"el baño",en:"bathroom",pron:"el BAH-nyoh",ex:"El baño está al final del pasillo."},
    {es:"la sala",en:"living room",pron:"lah SAH-lah",ex:"Vemos la tele en la sala."},
    {es:"el jardín",en:"garden",pron:"el har-DEEN",ex:"Mi abuela cuida el jardín."},
  ],
  Shopping:[
    {es:"¿Cuánto cuesta?",en:"How much does it cost?",pron:"KWAHN-toh KWES-tah",ex:"¿Cuánto cuesta esta camisa?"},
    {es:"barato",en:"cheap / inexpensive",pron:"bah-RAH-toh",ex:"Este mercado es muy barato."},
    {es:"caro",en:"expensive",pron:"KAH-roh",ex:"El restaurante es muy caro."},
    {es:"la tienda",en:"store / shop",pron:"lah TYEHN-dah",ex:"La tienda cierra a las ocho."},
    {es:"el precio",en:"price",pron:"el PREH-syoh",ex:"El precio es razonable."},
  ],
};

const VERBS = [
  {inf:"hablar",en:"to speak",type:"-AR",conj:{pres:{yo:"hablo",tú:"hablas",él:"habla",nosotros:"hablamos",vosotros:"habláis",ellos:"hablan"},pret:{yo:"hablé",tú:"hablaste",él:"habló",nosotros:"hablamos",vosotros:"hablasteis",ellos:"hablaron"},fut:{yo:"hablaré",tú:"hablarás",él:"hablará",nosotros:"hablaremos",vosotros:"hablaréis",ellos:"hablarán"}}},
  {inf:"comer",en:"to eat",type:"-ER",conj:{pres:{yo:"como",tú:"comes",él:"come",nosotros:"comemos",vosotros:"coméis",ellos:"comen"},pret:{yo:"comí",tú:"comiste",él:"comió",nosotros:"comimos",vosotros:"comisteis",ellos:"comieron"},fut:{yo:"comeré",tú:"comerás",él:"comerá",nosotros:"comeremos",vosotros:"comeréis",ellos:"comerán"}}},
  {inf:"vivir",en:"to live",type:"-IR",conj:{pres:{yo:"vivo",tú:"vives",él:"vive",nosotros:"vivimos",vosotros:"vivís",ellos:"viven"},pret:{yo:"viví",tú:"viviste",él:"vivió",nosotros:"vivimos",vosotros:"vivisteis",ellos:"vivieron"},fut:{yo:"viviré",tú:"vivirás",él:"vivirá",nosotros:"viviremos",vosotros:"viviréis",ellos:"vivirán"}}},
  {inf:"ser",en:"to be (permanent)",type:"Irregular",conj:{pres:{yo:"soy",tú:"eres",él:"es",nosotros:"somos",vosotros:"sois",ellos:"son"},pret:{yo:"fui",tú:"fuiste",él:"fue",nosotros:"fuimos",vosotros:"fuisteis",ellos:"fueron"},fut:{yo:"seré",tú:"serás",él:"será",nosotros:"seremos",vosotros:"seréis",ellos:"serán"}}},
  {inf:"estar",en:"to be (temporary)",type:"Irregular",conj:{pres:{yo:"estoy",tú:"estás",él:"está",nosotros:"estamos",vosotros:"estáis",ellos:"están"},pret:{yo:"estuve",tú:"estuviste",él:"estuvo",nosotros:"estuvimos",vosotros:"estuvisteis",ellos:"estuvieron"},fut:{yo:"estaré",tú:"estarás",él:"estará",nosotros:"estaremos",vosotros:"estaréis",ellos:"estarán"}}},
  {inf:"tener",en:"to have",type:"Irregular",conj:{pres:{yo:"tengo",tú:"tienes",él:"tiene",nosotros:"tenemos",vosotros:"tenéis",ellos:"tienen"},pret:{yo:"tuve",tú:"tuviste",él:"tuvo",nosotros:"tuvimos",vosotros:"tuvisteis",ellos:"tuvieron"},fut:{yo:"tendré",tú:"tendrás",él:"tendrá",nosotros:"tendremos",vosotros:"tendréis",ellos:"tendrán"}}},
  {inf:"ir",en:"to go",type:"Irregular",conj:{pres:{yo:"voy",tú:"vas",él:"va",nosotros:"vamos",vosotros:"vais",ellos:"van"},pret:{yo:"fui",tú:"fuiste",él:"fue",nosotros:"fuimos",vosotros:"fuisteis",ellos:"fueron"},fut:{yo:"iré",tú:"irás",él:"irá",nosotros:"iremos",vosotros:"iréis",ellos:"irán"}}},
  {inf:"hacer",en:"to do / make",type:"Irregular",conj:{pres:{yo:"hago",tú:"haces",él:"hace",nosotros:"hacemos",vosotros:"hacéis",ellos:"hacen"},pret:{yo:"hice",tú:"hiciste",él:"hizo",nosotros:"hicimos",vosotros:"hicisteis",ellos:"hicieron"},fut:{yo:"haré",tú:"harás",él:"hará",nosotros:"haremos",vosotros:"haréis",ellos:"harán"}}},
  {inf:"poder",en:"can / to be able to",type:"Irregular",conj:{pres:{yo:"puedo",tú:"puedes",él:"puede",nosotros:"podemos",vosotros:"podéis",ellos:"pueden"},pret:{yo:"pude",tú:"pudiste",él:"pudo",nosotros:"pudimos",vosotros:"pudisteis",ellos:"pudieron"},fut:{yo:"podré",tú:"podrás",él:"podrá",nosotros:"podremos",vosotros:"podréis",ellos:"podrán"}}},
  {inf:"querer",en:"to want / love",type:"Irregular",conj:{pres:{yo:"quiero",tú:"quieres",él:"quiere",nosotros:"queremos",vosotros:"queréis",ellos:"quieren"},pret:{yo:"quise",tú:"quisiste",él:"quiso",nosotros:"quisimos",vosotros:"quisisteis",ellos:"quisieron"},fut:{yo:"querré",tú:"querrás",él:"querrá",nosotros:"querremos",vosotros:"querréis",ellos:"querrán"}}},
];

const LISTENING_BANK = [
  {es:"Tengo mucha tarea esta noche.",q:"What does the speaker have a lot of tonight?",ans:"homework",hint:"tarea = homework"},
  {es:"Mi familia come la cena juntos.",q:"What does this family do together?",ans:"eat dinner",hint:"comer = to eat, juntos = together"},
  {es:"El examen de español es mañana.",q:"When is the Spanish exam?",ans:"tomorrow",hint:"mañana = tomorrow"},
  {es:"Me gusta mucho la música latina.",q:"What does the speaker like?",ans:"latin music",hint:"música = music"},
  {es:"Vivo cerca de la biblioteca.",q:"Where does the speaker live near?",ans:"library",hint:"biblioteca = library"},
  {es:"Mi hermana tiene quince años.",q:"How old is the sister?",ans:"15",hint:"quince = fifteen"},
  {es:"Hoy tengo que estudiar para el examen.",q:"What must the speaker do today?",ans:"study for the exam",hint:"estudiar = to study"},
  {es:"La clase de español es muy interesante.",q:"How is the class described?",ans:"interesting",hint:"interesante = interesting"},
  {es:"Mis padres trabajan todos los días.",q:"Who works every day?",ans:"parents",hint:"padres = parents"},
  {es:"Hace mucho calor hoy.",q:"What is the weather like?",ans:"very hot",hint:"calor = heat"},
  {es:"Necesito comprar un bolígrafo nuevo.",q:"What does the speaker need to buy?",ans:"a pen",hint:"bolígrafo = pen"},
];

const SPEAKING_BANK = [
  {en:"I like to eat breakfast with my family.",es:"Me gusta desayunar con mi familia.",hint:"me gusta... con mi familia"},
  {en:"I have to do my homework tonight.",es:"Tengo que hacer mi tarea esta noche.",hint:"tengo que hacer..."},
  {en:"My brother goes to school every day.",es:"Mi hermano va a la escuela todos los días.",hint:"va a la escuela..."},
  {en:"The Spanish exam is difficult.",es:"El examen de español es difícil.",hint:"el examen... es..."},
  {en:"I live near the library.",es:"Vivo cerca de la biblioteca.",hint:"vivo cerca de..."},
  {en:"We eat dinner together at home.",es:"Comemos la cena juntos en casa.",hint:"comemos... juntos"},
  {en:"Yesterday I studied for two hours.",es:"Ayer estudié por dos horas.",hint:"ayer estudié..."},
  {en:"Please speak more slowly.",es:"Por favor, habla más despacio.",hint:"por favor, habla..."},
  {en:"My grandparents are very nice.",es:"Mis abuelos son muy simpáticos.",hint:"mis abuelos son..."},
  {en:"I want to learn Spanish well.",es:"Quiero aprender español bien.",hint:"quiero aprender..."},
];

const ENCOURAGEMENTS = [
  {q:'"Every expert was once a beginner."',      a:"You showed up today — that\'s already a win! 🏆"},
  {q:'"Un poco cada día." (A little each day.)', a:"Consistency is your superpower. ¡Tú puedes!"},
  {q:'"The secret is to start."',                a:"You\'re doing it. Keep the momentum going!"},
  {q:'"Practice makes progress, not perfection."',a:"Each session makes Spanish feel more natural."},
  {q:'"Language is the road map of a culture."', a:"You\'re unlocking a whole new world! 🌎"},
  {q:'"It does not matter how slowly you go as long as you do not stop."',a:"Slow progress is still progress. ¡Sigue adelante!"},
];
